theme = "everforest_dark"

[editor]
mouse = false
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # use esc for , and ;
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh" # CTRL+y keybinding for opening yazi window in zellij

[editor.cursor-shape]
insert = "bar"
