[[language]]
name = "yaml"
auto-format = true
formatter = { command = "yamlfmt", args = ["-"] }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", ".git", ".venv/"]
file-types = ["py", "pyi", "ipynb"]
shebangs = ["python"]
auto-format = true
language-servers = ["ruff", "basedpyright"]

formatter = { command = "bash", args = [
  "-c",
  "uvx ruff check --fix - | uvx ruff format -"
] }

[language-server.ruff]
command = "uvx"
args = ["ruff", "server"]

[language-server.basedpyright]
command = "uvx"
args = ["--from", "basedpyright", "basedpyright-langserver", "--stdio"]

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }
auto-format = true

[[language]]
name = "jsonc"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsonc" ] }
auto-format = true
