[[language]]
name = "yaml"
auto-format = true
formatter = { command = "yamlfmt", args = ["-"] }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"
language-servers = ["rust-analyzer" ]
formatter = { command = "rustfmt" }
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer]
command = "rust-analyzer"
